spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
    port: 8080
  shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

logging:
  level:
    ROOT: INFO
    vn.lotusviet.hotelmgmt: INFO
